/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ChunkMetadata;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BatchQueuedChunkResponse
 */
public class BatchQueuedChunkResponseTest {
    private final BatchQueuedChunkResponse model = new BatchQueuedChunkResponse();

    /**
     * Model tests for BatchQueuedChunkResponse
     */
    @Test
    public void testBatchQueuedChunkResponse() {
        // TODO: test BatchQueuedChunkResponse
    }

    /**
     * Test the property 'chunkMetadata'
     */
    @Test
    public void chunkMetadataTest() {
        // TODO: test chunkMetadata
    }

    /**
     * Test the property 'posInQueue'
     */
    @Test
    public void posInQueueTest() {
        // TODO: test posInQueue
    }

}
