/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.FieldCondition;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChunkFilter
 */
public class ChunkFilterTest {
    private final ChunkFilter model = new ChunkFilter();

    /**
     * Model tests for ChunkFilter
     */
    @Test
    public void testChunkFilter() {
        // TODO: test ChunkFilter
    }

    /**
     * Test the property 'must'
     */
    @Test
    public void mustTest() {
        // TODO: test must
    }

    /**
     * Test the property 'mustNot'
     */
    @Test
    public void mustNotTest() {
        // TODO: test mustNot
    }

    /**
     * Test the property 'should'
     */
    @Test
    public void shouldTest() {
        // TODO: test should
    }

}
