/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ClientDatasetConfiguration
 */
public class ClientDatasetConfigurationTest {
    private final ClientDatasetConfiguration model = new ClientDatasetConfiguration();

    /**
     * Model tests for ClientDatasetConfiguration
     */
    @Test
    public void testClientDatasetConfiguration() {
        // TODO: test ClientDatasetConfiguration
    }

    /**
     * Test the property 'CREATE_CHUNK_FEATURE'
     */
    @Test
    public void CREATE_CHUNK_FEATURETest() {
        // TODO: test CREATE_CHUNK_FEATURE
    }

    /**
     * Test the property 'DATE_RANGE_VALUE'
     */
    @Test
    public void DATE_RANGE_VALUETest() {
        // TODO: test DATE_RANGE_VALUE
    }

    /**
     * Test the property 'DOCUMENT_UPLOAD_FEATURE'
     */
    @Test
    public void DOCUMENT_UPLOAD_FEATURETest() {
        // TODO: test DOCUMENT_UPLOAD_FEATURE
    }

    /**
     * Test the property 'FILE_NAME_KEY'
     */
    @Test
    public void FILE_NAME_KEYTest() {
        // TODO: test FILE_NAME_KEY
    }

    /**
     * Test the property 'FILTER_ITEMS'
     */
    @Test
    public void FILTER_ITEMSTest() {
        // TODO: test FILTER_ITEMS
    }

    /**
     * Test the property 'FRONTMATTER_VALS'
     */
    @Test
    public void FRONTMATTER_VALSTest() {
        // TODO: test FRONTMATTER_VALS
    }

    /**
     * Test the property 'IMAGE_RANGE_END_KEY'
     */
    @Test
    public void IMAGE_RANGE_END_KEYTest() {
        // TODO: test IMAGE_RANGE_END_KEY
    }

    /**
     * Test the property 'IMAGE_RANGE_START_KEY'
     */
    @Test
    public void IMAGE_RANGE_START_KEYTest() {
        // TODO: test IMAGE_RANGE_START_KEY
    }

    /**
     * Test the property 'LINES_BEFORE_SHOW_MORE'
     */
    @Test
    public void LINES_BEFORE_SHOW_MORETest() {
        // TODO: test LINES_BEFORE_SHOW_MORE
    }

    /**
     * Test the property 'SEARCH_QUERIES'
     */
    @Test
    public void SEARCH_QUERIESTest() {
        // TODO: test SEARCH_QUERIES
    }

    /**
     * Test the property 'SUGGESTED_QUERIES'
     */
    @Test
    public void SUGGESTED_QUERIESTest() {
        // TODO: test SUGGESTED_QUERIES
    }

}
