/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeleteTopicData
 */
public class DeleteTopicDataTest {
    private final DeleteTopicData model = new DeleteTopicData();

    /**
     * Model tests for DeleteTopicData
     */
    @Test
    public void testDeleteTopicData() {
        // TODO: test DeleteTopicData
    }

    /**
     * Test the property 'topicId'
     */
    @Test
    public void topicIdTest() {
        // TODO: test topicId
    }

}
