/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetGroupsForChunksData
 */
public class GetGroupsForChunksDataTest {
    private final GetGroupsForChunksData model = new GetGroupsForChunksData();

    /**
     * Model tests for GetGroupsForChunksData
     */
    @Test
    public void testGetGroupsForChunksData() {
        // TODO: test GetGroupsForChunksData
    }

    /**
     * Test the property 'chunkIds'
     */
    @Test
    public void chunkIdsTest() {
        // TODO: test chunkIds
    }

}
