/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrganizationUsageCount
 */
public class OrganizationUsageCountTest {
    private final OrganizationUsageCount model = new OrganizationUsageCount();

    /**
     * Model tests for OrganizationUsageCount
     */
    @Test
    public void testOrganizationUsageCount() {
        // TODO: test OrganizationUsageCount
    }

    /**
     * Test the property 'datasetCount'
     */
    @Test
    public void datasetCountTest() {
        // TODO: test datasetCount
    }

    /**
     * Test the property 'fileStorage'
     */
    @Test
    public void fileStorageTest() {
        // TODO: test fileStorage
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'messageCount'
     */
    @Test
    public void messageCountTest() {
        // TODO: test messageCount
    }

    /**
     * Test the property 'orgId'
     */
    @Test
    public void orgIdTest() {
        // TODO: test orgId
    }

    /**
     * Test the property 'userCount'
     */
    @Test
    public void userCountTest() {
        // TODO: test userCount
    }

}
