/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Range
 */
public class RangeTest {
    private final Range model = new Range();

    /**
     * Model tests for Range
     */
    @Test
    public void testRange() {
        // TODO: test Range
    }

    /**
     * Test the property 'gt'
     */
    @Test
    public void gtTest() {
        // TODO: test gt
    }

    /**
     * Test the property 'gte'
     */
    @Test
    public void gteTest() {
        // TODO: test gte
    }

    /**
     * Test the property 'lt'
     */
    @Test
    public void ltTest() {
        // TODO: test lt
    }

    /**
     * Test the property 'lte'
     */
    @Test
    public void lteTest() {
        // TODO: test lte
    }

}
