/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.ChunkFilter;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RecommendChunksRequest
 */
public class RecommendChunksRequestTest {
    private final RecommendChunksRequest model = new RecommendChunksRequest();

    /**
     * Model tests for RecommendChunksRequest
     */
    @Test
    public void testRecommendChunksRequest() {
        // TODO: test RecommendChunksRequest
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'negativeChunkIds'
     */
    @Test
    public void negativeChunkIdsTest() {
        // TODO: test negativeChunkIds
    }

    /**
     * Test the property 'negativeTrackingIds'
     */
    @Test
    public void negativeTrackingIdsTest() {
        // TODO: test negativeTrackingIds
    }

    /**
     * Test the property 'positiveChunkIds'
     */
    @Test
    public void positiveChunkIdsTest() {
        // TODO: test positiveChunkIds
    }

    /**
     * Test the property 'positiveTrackingIds'
     */
    @Test
    public void positiveTrackingIdsTest() {
        // TODO: test positiveTrackingIds
    }

}
