/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RegenerateMessageData
 */
public class RegenerateMessageDataTest {
    private final RegenerateMessageData model = new RegenerateMessageData();

    /**
     * Model tests for RegenerateMessageData
     */
    @Test
    public void testRegenerateMessageData() {
        // TODO: test RegenerateMessageData
    }

    /**
     * Test the property 'highlightCitations'
     */
    @Test
    public void highlightCitationsTest() {
        // TODO: test highlightCitations
    }

    /**
     * Test the property 'highlightDelimiters'
     */
    @Test
    public void highlightDelimitersTest() {
        // TODO: test highlightDelimiters
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'streamResponse'
     */
    @Test
    public void streamResponseTest() {
        // TODO: test streamResponse
    }

    /**
     * Test the property 'topicId'
     */
    @Test
    public void topicIdTest() {
        // TODO: test topicId
    }

}
