/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ScoreChunkDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchChunkQueryResponseBody
 */
public class SearchChunkQueryResponseBodyTest {
    private final SearchChunkQueryResponseBody model = new SearchChunkQueryResponseBody();

    /**
     * Model tests for SearchChunkQueryResponseBody
     */
    @Test
    public void testSearchChunkQueryResponseBody() {
        // TODO: test SearchChunkQueryResponseBody
    }

    /**
     * Test the property 'scoreChunks'
     */
    @Test
    public void scoreChunksTest() {
        // TODO: test scoreChunks
    }

    /**
     * Test the property 'totalChunkPages'
     */
    @Test
    public void totalChunkPagesTest() {
        // TODO: test totalChunkPages
    }

}
