/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.ChunkFilter;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchWithinGroupData
 */
public class SearchWithinGroupDataTest {
    private final SearchWithinGroupData model = new SearchWithinGroupData();

    /**
     * Model tests for SearchWithinGroupData
     */
    @Test
    public void testSearchWithinGroupData() {
        // TODO: test SearchWithinGroupData
    }

    /**
     * Test the property 'dateBias'
     */
    @Test
    public void dateBiasTest() {
        // TODO: test dateBias
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'groupTrackingId'
     */
    @Test
    public void groupTrackingIdTest() {
        // TODO: test groupTrackingId
    }

    /**
     * Test the property 'highlightDelimiters'
     */
    @Test
    public void highlightDelimitersTest() {
        // TODO: test highlightDelimiters
    }

    /**
     * Test the property 'highlightResults'
     */
    @Test
    public void highlightResultsTest() {
        // TODO: test highlightResults
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'scoreThreshold'
     */
    @Test
    public void scoreThresholdTest() {
        // TODO: test scoreThreshold
    }

    /**
     * Test the property 'searchType'
     */
    @Test
    public void searchTypeTest() {
        // TODO: test searchType
    }

    /**
     * Test the property 'useWeights'
     */
    @Test
    public void useWeightsTest() {
        // TODO: test useWeights
    }

}
