/*
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GroupScoreChunkDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchOverGroupsResponseBody
 */
public class SearchOverGroupsResponseBodyTest {
    private final SearchOverGroupsResponseBody model = new SearchOverGroupsResponseBody();

    /**
     * Model tests for SearchOverGroupsResponseBody
     */
    @Test
    public void testSearchOverGroupsResponseBody() {
        // TODO: test SearchOverGroupsResponseBody
    }

    /**
     * Test the property 'groupChunks'
     */
    @Test
    public void groupChunksTest() {
        // TODO: test groupChunks
    }

    /**
     * Test the property 'totalChunkPages'
     */
    @Test
    public void totalChunkPagesTest() {
        // TODO: test totalChunkPages
    }

}
